name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "My frist GitHub Actions Job"
            
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: list files
              run: ls

            - name: Read file
              run: cat README.md