name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu
        steps:
            - name: Welcome message
              run: echo "My frist GitHub Actions Job"

            - name: list files
              run: ls

            - name: Read file
              run: cat README.md