name: Generate ASCII Artwork

on: 
  push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay
        run: sudo apt-get install -y cowsay

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

      - name: Sleep for 30 s
        run: sleep 30

  test_job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10 s
        run: sleep 10

      - name: Test file exists
        run: grep -i "dragon" dragon.txt

  deploy_job_3:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          run: cat dragon.txt

        - name: List Repo Files
          run: echo Deploying...